### ISSUE TITLE
Bungeecord Support

### ISSUE THREAD

**Issue by WaldperlachFabi** [BGHDDevelopment/PunishmentGUIRecode#10]
Would be really amazing, thank you!

**Comment by Refrac** [comment]
BungeeCord support is not possible GUI's cannot be opened from bungeecord it does not support it.

**Comment by BGHDDevelopment** [comment]
Like said above sadly bungee does not support GUI's, so for now the workaround is to use MySQL for your punishment handler on each spigot server along with PunishmentGUI.
