### ISSUE TITLE
"Could not pass event InventoryClickEvent to Punish GUI v1.1.6"

### ISSUE THREAD

**Issue by LikeableGaming** [BGHDDevelopment/PunishmentGUIRecode#12]
Hi there, I'm having an issue when I click an item with a command attached. 

Console Error: https://pastebin.com/2SzGUJy5
Config: https://pastebin.com/4CYcByda

**Comment by Refrac** [comment]
@LikeableGaming You deleted a lot of the config options such as actions from items and commands the config is not meant to do that is why you are getting that error i recommend resetting back to default config.
