### ISSUE TITLE
Add support for Bedrock / Geyser users

### ISSUE THREAD

**Issue by DaddyRobLIVE** [BGHDDevelopment/PunishmentGUIRecode#16]
![image](https://github.com/user-attachments/assets/2803060d-3afc-4e79-a63b-028a403c7584)
![image](https://github.com/user-attachments/assets/f46f273f-5e79-48bf-beb9-49e3ea08c1cd)

The GUI works fine with java players but if you try to punish a bedrock player, it will allow you take items inside the GUI.
It will also be nice to sync this with Litebans by adding a command manually for each buttons instead of the plugin deciding what to do.

**Comment by BGHDDevelopment** [comment]
Bedrock support is not planned for now, however you can modify the commands for each button already? Please reach out on Discord if you run into any issues.
